[allowed_tables]
itens = ["nome"]
pharma = ["nome","cor"]
stock = ["id_pharma", "lote", "qnt", "dt_prazo", "dt_ent", "obs"]
stock_outs = ["id_stock", "usado"]

usuario = ["nome", "nome_completo", "cargo", "cpf"]

[allowed_pages]
PharmaStock = "modules/estoque/index.html"
Pessoas = "modules/Pessoas/index.html"

[allowed_subpages]
PharmaStock = [
    {dashboard = 'modules/estoque/pages/dashboard.html'},
    {completo = 'modules/estoque/pages/completo.html'},
    {movimentacao = 'modules/estoque/pages/movimentacao.html'},
    {controle = 'modules/estoque/pages/controle.html'}
]

Pessoas = [
    {users = 'modules/Pessoas/pages/users.html'},
    {cadastro = 'modules/Pessoas/pages/cadastro.html'},
    {access = 'modules/Pessoas/pages/access.html'},
]

[allowed_access_key]
cadastro = ["supervisor"]