[allowed_tables]
itens = ["nome"]
pharma = ["nome","cor"]
stock = ["id_pharma", "lote", "qnt", "dt_prazo", "dt_ent", "obs"]
stock_outs = ["id_stock", "usado"]

[allowed_pages]
PharmaStock = "modules/estoque/index.html"
itens = "modules/testes/itens.html"

[allowed_subpages]
PharmaStock = [
    {dashboard = 'modules/estoque/pages/dashboard.html'},
    {completo = 'modules/estoque/pages/completo.html'},
    {movimentacao = 'modules/estoque/pages/movimentacao.html'},
    {controle = 'modules/estoque/pages/controle.html'}
]